Algoritmo "AreaDoTriangulo"
// Descrição   :  Solicita a base e altura e calcula a area do triangulo depois divide por dois
// Autor(a)    : Danilo Keithi Makiya Nakasone
// Data atual  : 08/03/2022
Var
base, alt, area: real




Inicio
//Entrada
escreval ("digite a base do triangulo")
leia(base)
escreval ("digite a altura do triangulo")
leia(alt)

//processamento
area <- base*alt/2

//saida
escreval ("a base  do triangulo", area)




Fimalgoritmo