algoritmo "QuadradoNumeros"
// Função : Informe os valores para calcular o quadrado deles
// Autor :  Danilo Keithi Makiya Nakasone
// Data : 26/04/2022
// Seção de Declarações 
var

n1, n2, n3, n4: real

inicio
// Entrada
escreval("escreva o primeiro numero")
leia(n1)
escreval("escreva o segundo numero")
leia(n2)
escreval("escreva o terceiro numero")
leia(n3)
escreval("escreva o quato numero")

//processamento





fimalgoritmo
