Algoritmo "semnome"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Cinthia pinho
// Descrição   : Solicite um numero para saber se ele é par ou impar
// Autor(a)    : Danilo Keithi Makiya Nakasone

// Data atual  : 26/07/2022
Var
numero: inteiro


Inicio
//entrada
escreval("digite um numero inteiro")
leia(numero)

//processamento

se (numero mod 2 = 0) entao
escreval("O numero é par")

senao
("O numero é impar")

fimse


Fimalgoritmo