Algoritmo "semnome"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : cintia pinho
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Danilo eithi
// Data atual  : 23/08/2022
Var
cont, acu:inteiro


Inicio
escreval("-------------------LAÇO PARA---------------------------")

para cont de 1 ate 20 faca

escreval(cont)

fimpara


Fimalgoritmo