algoritmo "ConversaoDOlar"
// Função : informe a quantidade em dolar para converter
// Autor : Danilo Keithi Makiya Nakasone
// Data : 26/04/2022
// Seção de Declarações 
var
dolar, reais, conversao: real
inicio
//Entrada

escreval("digite o valor em real")
leia(reais)
escreval("digite a cotação do dolar")
leia(dolar)

//processamento

conversao <- (reais/dolar)


//saida

escreval(" a conversão é de:", conversao,"$")

fimalgoritmo
