algoritmo "conceito_nota"
// Função : solicite as notas do aluno e aplique o conceito solicitado
// Autor : Danilo Keithi
// Data : 21/06/2022
// Seção de Declarações 
var
nf, nt, n1, n2: real
A, B, C, D, E: logico

inicio
// entrada
escreval("Digite a primeira nota")
leia(n1)
escreval "Digite a sugunda nota")
leia(n2)
escreval("Digite a nota total dos trabalhos (max 10.)")
leia(nt)

//processamento

nf <- (n1+n2+nt)/3
A <- nf >=





fimalgoritmo
