Algoritmo "semnome"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Cintia pinho
// Descrição   : Fator numero
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 20/09/2022
Var
num1, cont, fator : inteiro


Inicio
fator <- 1
escreval("Digite um numero para fatorar OBS: numero maior que 0")
leia(num1)

para cont de num1 ate 1 passo -1 faca
fator <- fator*cont

fimpara

escreval("O fator de", num1, " é ", fator)





Fimalgoritmo