Algoritmo "EXERCICIO3"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : escreve numeros impares de 100 a 200
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 06/09/2022
Var
impar, n :inteiro


Inicio
escreval("digite 1 para começar")
leia(n)
limpatela

para  impar de 100 ate 200 faca
se (impar%2=1) entao
escreval(impar)
fimse
fimpara


Fimalgoritmo