Algoritmo "Exercicio 2"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : cintia pinho
// Descrição   : peça um número depois faça a tabuada dele
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 06/09/2022
Var
nu, cont: inteiro


Inicio
Escreval("digite um numero para que o programa faça a tabuada dele")
leia(nu)

para cont de 1 ate 10 passo 1 faca

cont <- cont*nu

escreval(cont)


fimpara






Fimalgoritmo