Algoritmo "semnome"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Cintia pinho
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Danilo Keithi
// Data atual  : 06/09/2022
Var
n1, n2, cont : inteiro


Inicio
escreval("digite o número do começo")
leia(n1)
escreval("digite o número do final")
leia(n2)

para cont de n1 ate n2 faca

escreval(cont)

fimpara







Fimalgoritmo