Algoritmo "EXERCICIO15"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Cintia Pinho
// Descrição   :  Melhor escola de Ribeirão Pires
// Autor(a)    : Danilo Keithi
// Data atual  : 20/09/2022
Var
esc: caractere


Inicio
repita
escreval ("Qual é a melhor escola de Ribeirão Pires?")
leia(esc)
ate((esc="Etec MCM") ou (esc="ETEC MCM") ou (esc="etec mcm"))


Fimalgoritmo